### ISSUE TITLE
[FEATURE] Should devDependencies be pruned?

### ISSUE THREAD

**Issue by isaacs** [npm/minify-registry-metadata#5]
# What / Why

Since `devDependencies` are only relevant at the top level, perhaps they don't need to be in the corgi doc.  I notice that some packages have quite a lot of these.  Picking one more or less at random from the current backfill operation in progress:

```
Permissions Size User   Date Modified    Name
.rw-r--r--  349k isaacs 2020-02-13 22:59 olasearch-core.json
.rw-r--r--  203k isaacs 2020-02-13 23:00 olasearch-core.no-dev-deps.json
```

That's almost 150kb saved.

**Comment by wraithgar** [comment]
The package-deps-api endpoint uses corgis so we can't land this.
